name: Run Scrappers

on:
  repository_dispatch:
    types: [run_scrappers]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file: [scrapper19.js, scrapper20.js, scrapper21.js, scrapper22.js, scrapper23.js, scrapper24.js, scrapper25.js, scrapper26.js, scrapper27.js]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Run Scraper
        run: node ${{ matrix.file }}
